// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwNUQLPp8OSIL8B1ItK9HhpL7S6hWgpVs',
    appId: '1:694587553891:web:8a4fad5ef06a4e9b262056',
    messagingSenderId: '694587553891',
    projectId: 'shoely-app',
    authDomain: 'shoely-app.firebaseapp.com',
    storageBucket: 'shoely-app.firebasestorage.app',
    measurementId: 'G-4G10T66FNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeEf7q4ih_L7vf8o1S_Fzvx5OakM-wKE0',
    appId: '1:694587553891:android:5cd327174270bf3e262056',
    messagingSenderId: '694587553891',
    projectId: 'shoely-app',
    storageBucket: 'shoely-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdAdMyDpyQgUUs4YQd9fl4ccx9EYp9ciA',
    appId: '1:694587553891:ios:209a39ed835b8712262056',
    messagingSenderId: '694587553891',
    projectId: 'shoely-app',
    storageBucket: 'shoely-app.firebasestorage.app',
    androidClientId: '694587553891-0gvcjfqn9fghjt9esl5ehfb2t5fpt5dr.apps.googleusercontent.com',
    iosClientId: '694587553891-l5imuspl87mct675gro33vok5obquc3r.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoelyDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdAdMyDpyQgUUs4YQd9fl4ccx9EYp9ciA',
    appId: '1:694587553891:ios:209a39ed835b8712262056',
    messagingSenderId: '694587553891',
    projectId: 'shoely-app',
    storageBucket: 'shoely-app.firebasestorage.app',
    androidClientId: '694587553891-0gvcjfqn9fghjt9esl5ehfb2t5fpt5dr.apps.googleusercontent.com',
    iosClientId: '694587553891-l5imuspl87mct675gro33vok5obquc3r.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoelyDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwNUQLPp8OSIL8B1ItK9HhpL7S6hWgpVs',
    appId: '1:694587553891:web:147b0edc98cf4529262056',
    messagingSenderId: '694587553891',
    projectId: 'shoely-app',
    authDomain: 'shoely-app.firebaseapp.com',
    storageBucket: 'shoely-app.firebasestorage.app',
    measurementId: 'G-TEG89D33S5',
  );
}
